import Head from "next/head";
import styles from "@/styles/Home.module.scss";
import Image from 'next/image';
import { Input } from '../components/form/input'
import { ButtonForm } from '../components/button/button'
import { BigTitle } from "../components/titles/bigTitle";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Register</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.container}>

        <section className={styles.containerForm}>
          <div className={styles.containerInput}>

            <BigTitle>REGISTER</BigTitle>

            <form action="#">
              <Input
                type='text'
                placeholder="Name"
                max={50} />

              <Input
                type='email'
                placeholder="E-mail"
                max={50} />

              <Input
                type='text'
                placeholder="Password"
                max={8} />

              <ButtonForm>Create account</ButtonForm>

              <Link href={'/'}>Login</Link>
            </form>
          </div>
          <div className={styles.containerIMG}>
            <div className={styles.containerEffect}>

              <Image
                src="/image/task_11283937.png" // Caminho relativo à pasta public
                alt="Icon Web, Check tasks"
                width={64}
                height={64}
              />

              <h2>Organize your Tasks</h2>
            </div>
          </div>
        </section>
      </main>
    </>
  );
}
